export const quotes = [
	'The average lifespan of an eyelash is five months.',
	"The most iconic donut shop in Hollywood is Randy's Donuts, appearing in movies like Crocodile Dundee and Iron Man 2.",
	'There are more than 1,100 known tributaries flowing into the Amazon River.',
	'On August 26, 1883, Krakatoa erupted in the largest explosion recorded in history, heard 2,200 miles away in Madagascar.',
	'A cloud weighs around a million tonnes despite floating in the air.',
	'Bananas are radioactive due to containing the natural isotope potassium-40.',
	'Your body is around 280 times more radioactive than a banana.',
	"There's no such thing as a perfectly straight line - zoom in close enough and you'll spot irregularities.",
	"Water might not actually be wet - most scientists define wetness as a liquid's ability to maintain contact with a solid surface.",
	'LEGO bricks can withstand compression better than concrete and support 375,000 other bricks before failing.',
	'Komodo dragons can have virgin births through parthenogenesis - females can lay fertile eggs without males.',
	'Octopuses have three hearts, each with slightly different roles.',
	'Honey never spoils - archaeologists have found edible honey in ancient Egyptian tombs.',
	"A group of flamingos is called a 'flamboyance'.",
	'Sharks have been around longer than trees - sharks existed 400 million years ago, trees 350 million years ago.',
	"The human brain uses 20% of the body's total energy despite being only 2% of body weight.",
	'Wombat poop is cube-shaped to prevent it from rolling away and marking territory.',
	"A shrimp's heart is in its head.",
	'The shortest war in history lasted 38-45 minutes between Britain and Zanzibar in 1896.',
	'Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.',
	'Oxford University is older than the Aztec Empire - Oxford founded around 1096, Aztecs around 1345.',
	'There are more possible games of chess than atoms in the observable universe.',
	"A group of pandas is called an 'embarrassment'.",
	'Dolphins have names for each other - they use signature whistles.',
	"The unicorn is Scotland's national animal.",
	'It would take 9.5 years to walk to the moon if you could walk in a straight line.',
	'A day on Venus is longer than its year - Venus rotates once every 243 Earth days but orbits the sun every 225 Earth days.',
	'The Great Wall of China is not visible from space with the naked eye, contrary to popular belief.',
	'Butterflies taste with their feet and smell with their antennae.',
	"A group of crows is called a 'murder', while a group of ravens is called an 'unkindness'.",
	"The dot over a lowercase 'i' or 'j' is called a tittle.",
	'Penguins can jump as high as 6 feet out of water.',
	'The longest recorded flight of a chicken is 13 seconds.',
	'A sneeze travels out of your mouth at over 100 mph.',
	'The human nose can detect over 1 trillion different scents.',
	'Lightning strikes the Earth about 100 times per second.',
	"A group of owls is called a 'parliament'.",
	'The tongue is the strongest muscle in the human body relative to its size.',
	'Sea otters hold hands while sleeping to prevent drifting apart.',
	"McDonald's golden arches are one of the most recognized symbols worldwide."
];

export function getRandomQuote(): string {
	return quotes[Math.floor(Math.random() * quotes.length)];
}
