<script lang="ts">
	import { onMount } from 'svelte';

	interface Props {
		value: string;
		isGenerating?: boolean;
		onSend: () => void;
		onStop?: () => void;
		placeholder?: string;
	}

	let {
		value = $bindable(),
		isGenerating = false,
		onSend,
		onStop,
		placeholder = 'Share your thoughts...'
	}: Props = $props();

	let inputElement: HTMLTextAreaElement | undefined = $state();

	function handleKeyDown(e: KeyboardEvent) {
		if (e.key === 'Enter' && !e.shiftKey) {
			e.preventDefault();
			if (!isGenerating && value.trim()) {
				onSend();
			}
		}
	}

	function focusAfterMount(node: HTMLTextAreaElement) {
		if (node && !node.disabled) {
			node.focus();
		}
	}

	export function focus() {
		if (inputElement) {
			inputElement.focus();
		}
	}

	onMount(() => {
		focus();
	});
</script>

<div class="input-area">
	<div class="input-decoration">
		<svg viewBox="0 0 100 4" width="100%" height="4">
			<path
				d="M0,2 Q25,0.5 50,2 T100,2"
				stroke="var(--earth-medium)"
				stroke-width="1"
				fill="none"
				opacity="0.4"
			/>
		</svg>
	</div>

	<div class="message-input" class:is-disabled={isGenerating}>
		<div class="input-accent">
			<svg viewBox="0 0 12 12" width="12" height="12">
				<circle cx="6" cy="6" r="3" fill="var(--sage)" opacity="0.6" />
			</svg>
		</div>
		<textarea
			id="chat"
			bind:this={inputElement}
			bind:value
			{placeholder}
			rows="1"
			use:focusAfterMount
			onkeydown={handleKeyDown}
		></textarea>
		{#if isGenerating && onStop}
			<button onclick={onStop} class="stop-btn-inline" aria-label="Stop generation">
				<svg viewBox="0 0 16 16" width="16" height="16" fill="currentColor">
					<rect x="4" y="4" width="8" height="8" rx="1" />
				</svg>
			</button>
		{:else}
			<button
				onclick={onSend}
				disabled={isGenerating || !value.trim()}
				class="send-btn"
				aria-label="Send message"
			>
				<svg
					viewBox="0 0 20 20"
					width="18"
					height="18"
					stroke="currentColor"
					stroke-width="2"
					fill="none"
					stroke-linecap="round"
					stroke-linejoin="round"
				>
					<line x1="2" y1="10" x2="18" y2="10"></line>
					<polyline points="12,4 18,10 12,16"></polyline>
				</svg>
			</button>
		{/if}
	</div>

	<div class="disclaimer">
		<svg viewBox="0 0 12 12" width="12" height="12" class="disclaimer-icon">
			<circle
				cx="6"
				cy="6"
				r="4"
				fill="none"
				stroke="var(--earth-dark)"
				stroke-width="1"
				opacity="0.6"
			/>
			<circle cx="6" cy="6" r="1" fill="var(--earth-dark)" opacity="0.6" />
		</svg>
		Responses are generated by AI and may contain inaccuracies.
	</div>
</div>

<style>
	.input-area {
		padding: 1.5rem 2rem;
		background: linear-gradient(135deg, rgba(230, 221, 212, 0.6) 0%, rgba(245, 241, 235, 0.8) 100%);
		backdrop-filter: blur(10px);
		border-top: 1px solid var(--earth-medium);
		position: relative;
		overflow: hidden;
	}

	.input-decoration {
		position: absolute;
		top: 0;
		left: 0;
		right: 0;
		height: 4px;
		padding: 0 1rem;
		box-sizing: border-box;
	}

	.message-input {
		display: flex;
		align-items: flex-end;
		background: rgba(245, 241, 235, 0.9);
		backdrop-filter: blur(10px);
		border: 1px solid var(--earth-medium);
		padding: 0;
		box-shadow:
			0 4px 15px rgba(139, 111, 71, 0.1),
			inset 0 1px 0 rgba(255, 255, 255, 0.8);
		border-radius: 1.5rem;
		overflow: hidden;
		transition: all 0.3s ease;
		margin-bottom: 1rem;
		position: relative;
	}

	.input-accent {
		position: absolute;
		top: -6px;
		left: 1rem;
		z-index: 1;
		background: rgba(245, 241, 235, 0.9);
		padding: 2px 4px;
		border-radius: 50%;
	}

	.message-input:hover:not(.is-disabled) {
		transform: translateY(-1px);
		box-shadow:
			0 6px 20px rgba(139, 111, 71, 0.15),
			inset 0 1px 0 rgba(255, 255, 255, 0.9);
	}

	.message-input:focus-within:not(.is-disabled) {
		border-color: var(--mocha-mousse);
		box-shadow:
			0 6px 20px rgba(139, 111, 71, 0.2),
			inset 0 1px 0 rgba(255, 255, 255, 0.9),
			0 0 0 3px rgba(167, 132, 106, 0.1);
	}

	.message-input.is-disabled {
		background: rgba(168, 160, 144, 0.3);
		opacity: 0.7;
	}

	textarea {
		flex-grow: 1;
		padding: 1rem 1.25rem;
		padding-top: 1.25rem;
		border: none;
		resize: none;
		font-family: 'Space Grotesk', 'Georgia', serif;
		font-size: 1rem;
		font-weight: 400;
		line-height: 1.5;
		background: transparent;
		min-height: 22px;
		max-height: 120px;
		outline: none;
		color: var(--text-primary);
		letter-spacing: 0.01em;
	}

	textarea::placeholder {
		color: var(--text-light);
		font-weight: 400;
		font-style: italic;
	}

	.send-btn {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 40px;
		height: 40px;
		margin: 8px;
		align-self: center;
		background: linear-gradient(135deg, var(--mocha-mousse), var(--clay));
		color: var(--cream);
		border: 1px solid var(--earth-dark);
		border-radius: 50%;
		cursor: pointer;
		transition: all 0.3s ease;
		box-shadow:
			0 3px 10px rgba(139, 111, 71, 0.2),
			inset 0 1px 0 rgba(255, 255, 255, 0.2);
	}

	.send-btn:hover:not(:disabled) {
		background: linear-gradient(135deg, var(--clay), var(--mocha-mousse));
		transform: translateY(-2px);
		box-shadow:
			0 5px 15px rgba(139, 111, 71, 0.3),
			inset 0 1px 0 rgba(255, 255, 255, 0.3);
	}

	.send-btn:active:not(:disabled) {
		transform: translateY(0);
		box-shadow:
			0 2px 8px rgba(139, 111, 71, 0.3),
			inset 0 1px 0 rgba(255, 255, 255, 0.1);
	}

	.send-btn:disabled {
		background: var(--stone);
		color: var(--text-light);
		cursor: not-allowed;
		opacity: 0.5;
		transform: none;
		box-shadow: none;
	}

	.stop-btn-inline {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 40px;
		height: 40px;
		margin: 8px;
		align-self: center;
		background: linear-gradient(135deg, #c07860, #a86550);
		color: var(--cream);
		border: 1px solid #8b5a3c;
		border-radius: 50%;
		cursor: pointer;
		transition: all 0.3s ease;
		box-shadow:
			0 3px 10px rgba(139, 111, 71, 0.2),
			inset 0 1px 0 rgba(255, 255, 255, 0.2);
		animation: gentlePulse 2s ease-in-out infinite;
	}

	@keyframes gentlePulse {
		0%,
		100% {
			transform: scale(1);
		}
		50% {
			transform: scale(1.05);
		}
	}

	.stop-btn-inline:hover {
		background: linear-gradient(135deg, #d08870, #b87560);
		transform: translateY(-2px);
		box-shadow:
			0 5px 15px rgba(139, 111, 71, 0.3),
			inset 0 1px 0 rgba(255, 255, 255, 0.3);
		animation: none;
	}

	.stop-btn-inline:active {
		transform: translateY(0);
		box-shadow:
			0 2px 8px rgba(139, 111, 71, 0.3),
			inset 0 1px 0 rgba(255, 255, 255, 0.1);
	}

	.disclaimer {
		font-size: 0.8rem;
		font-weight: 400;
		color: var(--text-light);
		text-align: center;
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 0.5rem;
		margin: 0 auto;
		width: fit-content;
		max-width: 400px;
		font-style: italic;
		letter-spacing: 0.01em;
	}

	.disclaimer-icon {
		flex-shrink: 0;
		opacity: 0.7;
	}

	@media (max-width: 600px) {
		.input-area {
			padding: 1.25rem 1.5rem;
		}

		textarea {
			font-size: 0.95rem;
			padding: 0.875rem 1rem;
			padding-top: 1rem;
		}

		.send-btn,
		.stop-btn-inline {
			width: 36px;
			height: 36px;
		}

		.disclaimer {
			font-size: 0.75rem;
			width: 100%;
			max-width: none;
		}

		.input-accent {
			display: none;
		}
	}
</style>
